### ISSUE TITLE
Please include build instructions for Linux

### ISSUE THREAD

**Issue by johnblommers** [luebking/sqriptor#1]
So I tried to build sqriptor on Pop!_OS (an Ubuntu 21.04 based distro) using a fairly naive approach by downloading the ZIP file, extracting the archive and:

```bash
cd sqriptor-main
qmake
make 
g++ -c -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o sqriptor.o sqriptor.cpp
sqriptor.cpp:19:10: fatal error: QAction: No such file or directory
   19 | #include <QAction>
      |          ^~~~~~~~~
compilation terminated.
```
Would you be able to shed light on the build procedure?

**Update**
Aha! My system was missing a dependency:

```bash
sudo apt install libqscintilla2-qt5-dev
```

**Comment by luebking** [comment]
> Aha! My system was missing a dependency:

Yup.
Did you not get a warning from qmake about qscintilla2.prf being missing or similar?

**Comment by johnblommers** [comment]
`qmake` gave no warnings and so I proceeded with `make` and got the error. Then I chanced to look at PKGBUILD and found therein the critical clue to solve the mystery.
