### ISSUE TITLE
 Compiling error

### ISSUE THREAD

**Issue by mlmatlock** [luebking/sqriptor#5]
Attempting to upgrade from b03e677 to 326cf6f (Arch, fully updated).

Full compiler output:

https://0x0.st/XVTW.txt

**Comment by luebking** [comment]
You're using (likely) an old PKGBUILD and qt5; I'll see to get it build w/ that again but you likely want to move on to Qt6?

**Comment by luebking** [comment]
Keywords broken? Me stupid?
https://github.com/luebking/sqriptor/commit/fb35229b7c423605544d35154f99df52ec0afa62

**Comment by mlmatlock** [comment]
> You're using (likely) an old PKGBUILD and qt5; I'll see to get it build w/ that again but you likely want to move on to Qt6?

`slaps himself upside the head`

Sorry for the noise. Didn't update the PKGBUILD.  All good now.

Thanks!
